#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQLYSHK
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLYSHK")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIAYKHAISINH(GIAYKHAISINH instance);
    partial void UpdateGIAYKHAISINH(GIAYKHAISINH instance);
    partial void DeleteGIAYKHAISINH(GIAYKHAISINH instance);
    partial void InsertGIAYTAMVANG(GIAYTAMVANG instance);
    partial void UpdateGIAYTAMVANG(GIAYTAMVANG instance);
    partial void DeleteGIAYTAMVANG(GIAYTAMVANG instance);
    partial void InsertNHANKHAU(NHANKHAU instance);
    partial void UpdateNHANKHAU(NHANKHAU instance);
    partial void DeleteNHANKHAU(NHANKHAU instance);
    partial void InsertPHIEUNHAPKHAU(PHIEUNHAPKHAU instance);
    partial void UpdatePHIEUNHAPKHAU(PHIEUNHAPKHAU instance);
    partial void DeletePHIEUNHAPKHAU(PHIEUNHAPKHAU instance);
    partial void InsertPHIEUTACHKHAU(PHIEUTACHKHAU instance);
    partial void UpdatePHIEUTACHKHAU(PHIEUTACHKHAU instance);
    partial void DeletePHIEUTACHKHAU(PHIEUTACHKHAU instance);
    partial void InsertPHIEUTHAYDOICHUHO(PHIEUTHAYDOICHUHO instance);
    partial void UpdatePHIEUTHAYDOICHUHO(PHIEUTHAYDOICHUHO instance);
    partial void DeletePHIEUTHAYDOICHUHO(PHIEUTHAYDOICHUHO instance);
    partial void InsertPHIEUTU(PHIEUTU instance);
    partial void UpdatePHIEUTU(PHIEUTU instance);
    partial void DeletePHIEUTU(PHIEUTU instance);
    partial void InsertSOHOKHAU(SOHOKHAU instance);
    partial void UpdateSOHOKHAU(SOHOKHAU instance);
    partial void DeleteSOHOKHAU(SOHOKHAU instance);
    partial void InsertSOTAMTRU(SOTAMTRU instance);
    partial void UpdateSOTAMTRU(SOTAMTRU instance);
    partial void DeleteSOTAMTRU(SOTAMTRU instance);
    #endregion
		
		public DbDataContext() : 
				base(global::WpfQLYSHK.Properties.Settings.Default.QLYSHKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIAYKHAISINH> GIAYKHAISINHs
		{
			get
			{
				return this.GetTable<GIAYKHAISINH>();
			}
		}
		
		public System.Data.Linq.Table<GIAYTAMVANG> GIAYTAMVANGs
		{
			get
			{
				return this.GetTable<GIAYTAMVANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANKHAU> NHANKHAUs
		{
			get
			{
				return this.GetTable<NHANKHAU>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPKHAU> PHIEUNHAPKHAUs
		{
			get
			{
				return this.GetTable<PHIEUNHAPKHAU>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTACHKHAU> PHIEUTACHKHAUs
		{
			get
			{
				return this.GetTable<PHIEUTACHKHAU>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHAYDOICHUHO> PHIEUTHAYDOICHUHOs
		{
			get
			{
				return this.GetTable<PHIEUTHAYDOICHUHO>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTU> PHIEUTUs
		{
			get
			{
				return this.GetTable<PHIEUTU>();
			}
		}
		
		public System.Data.Linq.Table<SOHOKHAU> SOHOKHAUs
		{
			get
			{
				return this.GetTable<SOHOKHAU>();
			}
		}
		
		public System.Data.Linq.Table<SOTAMTRU> SOTAMTRUs
		{
			get
			{
				return this.GetTable<SOTAMTRU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAYKHAISINH")]
	public partial class GIAYKHAISINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGIAYKHAISINH;
		
		private int _MANHANKHAUME;
		
		private int _MANHANKHAUBE;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
		private EntityRef<NHANKHAU> _NHANKHAU1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGIAYKHAISINHChanging(int value);
    partial void OnMAGIAYKHAISINHChanged();
    partial void OnMANHANKHAUMEChanging(int value);
    partial void OnMANHANKHAUMEChanged();
    partial void OnMANHANKHAUBEChanging(int value);
    partial void OnMANHANKHAUBEChanged();
    #endregion
		
		public GIAYKHAISINH()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			this._NHANKHAU1 = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAYKHAISINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAYKHAISINH
		{
			get
			{
				return this._MAGIAYKHAISINH;
			}
			set
			{
				if ((this._MAGIAYKHAISINH != value))
				{
					this.OnMAGIAYKHAISINHChanging(value);
					this.SendPropertyChanging();
					this._MAGIAYKHAISINH = value;
					this.SendPropertyChanged("MAGIAYKHAISINH");
					this.OnMAGIAYKHAISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUME", DbType="Int NOT NULL")]
		public int MANHANKHAUME
		{
			get
			{
				return this._MANHANKHAUME;
			}
			set
			{
				if ((this._MANHANKHAUME != value))
				{
					if (this._NHANKHAU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUMEChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUME = value;
					this.SendPropertyChanged("MANHANKHAUME");
					this.OnMANHANKHAUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAUBE", DbType="Int NOT NULL")]
		public int MANHANKHAUBE
		{
			get
			{
				return this._MANHANKHAUBE;
			}
			set
			{
				if ((this._MANHANKHAUBE != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUBEChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAUBE = value;
					this.SendPropertyChanged("MANHANKHAUBE");
					this.OnMANHANKHAUBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYKHAISINH", Storage="_NHANKHAU", ThisKey="MANHANKHAUBE", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.GIAYKHAISINHs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.GIAYKHAISINHs.Add(this);
						this._MANHANKHAUBE = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAUBE = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYKHAISINH1", Storage="_NHANKHAU1", ThisKey="MANHANKHAUME", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU1
		{
			get
			{
				return this._NHANKHAU1.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU1.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU1.Entity = null;
						previousValue.GIAYKHAISINHs1.Remove(this);
					}
					this._NHANKHAU1.Entity = value;
					if ((value != null))
					{
						value.GIAYKHAISINHs1.Add(this);
						this._MANHANKHAUME = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAUME = default(int);
					}
					this.SendPropertyChanged("NHANKHAU1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAYTAMVANG")]
	public partial class GIAYTAMVANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private int _MAGIAYTAMVANG;
		
		private System.DateTime _NGAYDI;
		
		private System.DateTime _NGAYVE;
		
		private string _NOIDI;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMAGIAYTAMVANGChanging(int value);
    partial void OnMAGIAYTAMVANGChanged();
    partial void OnNGAYDIChanging(System.DateTime value);
    partial void OnNGAYDIChanged();
    partial void OnNGAYVEChanging(System.DateTime value);
    partial void OnNGAYVEChanged();
    partial void OnNOIDIChanging(string value);
    partial void OnNOIDIChanged();
    #endregion
		
		public GIAYTAMVANG()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAYTAMVANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAYTAMVANG
		{
			get
			{
				return this._MAGIAYTAMVANG;
			}
			set
			{
				if ((this._MAGIAYTAMVANG != value))
				{
					this.OnMAGIAYTAMVANGChanging(value);
					this.SendPropertyChanging();
					this._MAGIAYTAMVANG = value;
					this.SendPropertyChanged("MAGIAYTAMVANG");
					this.OnMAGIAYTAMVANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDI", DbType="Date NOT NULL")]
		public System.DateTime NGAYDI
		{
			get
			{
				return this._NGAYDI;
			}
			set
			{
				if ((this._NGAYDI != value))
				{
					this.OnNGAYDIChanging(value);
					this.SendPropertyChanging();
					this._NGAYDI = value;
					this.SendPropertyChanged("NGAYDI");
					this.OnNGAYDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVE", DbType="Date NOT NULL")]
		public System.DateTime NGAYVE
		{
			get
			{
				return this._NGAYVE;
			}
			set
			{
				if ((this._NGAYVE != value))
				{
					this.OnNGAYVEChanging(value);
					this.SendPropertyChanging();
					this._NGAYVE = value;
					this.SendPropertyChanged("NGAYVE");
					this.OnNGAYVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDI", DbType="Char(256)")]
		public string NOIDI
		{
			get
			{
				return this._NOIDI;
			}
			set
			{
				if ((this._NOIDI != value))
				{
					this.OnNOIDIChanging(value);
					this.SendPropertyChanging();
					this._NOIDI = value;
					this.SendPropertyChanged("NOIDI");
					this.OnNOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYTAMVANG", Storage="_NHANKHAU", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.GIAYTAMVANGs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.GIAYTAMVANGs.Add(this);
						this._MANHANKHAU = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAU = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANKHAU")]
	public partial class NHANKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private System.Nullable<int> _MASHK;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _QUOCTICH;
		
		private string _QUANHEVOICHUHO;
		
		private string _CMND;
		
		private EntitySet<GIAYKHAISINH> _GIAYKHAISINHs;
		
		private EntitySet<GIAYKHAISINH> _GIAYKHAISINHs1;
		
		private EntitySet<GIAYTAMVANG> _GIAYTAMVANGs;
		
		private EntitySet<PHIEUNHAPKHAU> _PHIEUNHAPKHAUs;
		
		private EntitySet<PHIEUTACHKHAU> _PHIEUTACHKHAUs;
		
		private EntitySet<PHIEUTHAYDOICHUHO> _PHIEUTHAYDOICHUHOs;
		
		private EntitySet<PHIEUTU> _PHIEUTUs;
		
		private EntityRef<SOHOKHAU> _SOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMASHKChanging(System.Nullable<int> value);
    partial void OnMASHKChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnQUANHEVOICHUHOChanging(string value);
    partial void OnQUANHEVOICHUHOChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    #endregion
		
		public NHANKHAU()
		{
			this._GIAYKHAISINHs = new EntitySet<GIAYKHAISINH>(new Action<GIAYKHAISINH>(this.attach_GIAYKHAISINHs), new Action<GIAYKHAISINH>(this.detach_GIAYKHAISINHs));
			this._GIAYKHAISINHs1 = new EntitySet<GIAYKHAISINH>(new Action<GIAYKHAISINH>(this.attach_GIAYKHAISINHs1), new Action<GIAYKHAISINH>(this.detach_GIAYKHAISINHs1));
			this._GIAYTAMVANGs = new EntitySet<GIAYTAMVANG>(new Action<GIAYTAMVANG>(this.attach_GIAYTAMVANGs), new Action<GIAYTAMVANG>(this.detach_GIAYTAMVANGs));
			this._PHIEUNHAPKHAUs = new EntitySet<PHIEUNHAPKHAU>(new Action<PHIEUNHAPKHAU>(this.attach_PHIEUNHAPKHAUs), new Action<PHIEUNHAPKHAU>(this.detach_PHIEUNHAPKHAUs));
			this._PHIEUTACHKHAUs = new EntitySet<PHIEUTACHKHAU>(new Action<PHIEUTACHKHAU>(this.attach_PHIEUTACHKHAUs), new Action<PHIEUTACHKHAU>(this.detach_PHIEUTACHKHAUs));
			this._PHIEUTHAYDOICHUHOs = new EntitySet<PHIEUTHAYDOICHUHO>(new Action<PHIEUTHAYDOICHUHO>(this.attach_PHIEUTHAYDOICHUHOs), new Action<PHIEUTHAYDOICHUHO>(this.detach_PHIEUTHAYDOICHUHOs));
			this._PHIEUTUs = new EntitySet<PHIEUTU>(new Action<PHIEUTU>(this.attach_PHIEUTUs), new Action<PHIEUTU>(this.detach_PHIEUTUs));
			this._SOHOKHAU = default(EntityRef<SOHOKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASHK", DbType="Int")]
		public System.Nullable<int> MASHK
		{
			get
			{
				return this._MASHK;
			}
			set
			{
				if ((this._MASHK != value))
				{
					if (this._SOHOKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASHKChanging(value);
					this.SendPropertyChanging();
					this._MASHK = value;
					this.SendPropertyChanged("MASHK");
					this.OnMASHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="Char(256)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="Char(256)")]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANHEVOICHUHO", DbType="Char(256)")]
		public string QUANHEVOICHUHO
		{
			get
			{
				return this._QUANHEVOICHUHO;
			}
			set
			{
				if ((this._QUANHEVOICHUHO != value))
				{
					this.OnQUANHEVOICHUHOChanging(value);
					this.SendPropertyChanging();
					this._QUANHEVOICHUHO = value;
					this.SendPropertyChanged("QUANHEVOICHUHO");
					this.OnQUANHEVOICHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYKHAISINH", Storage="_GIAYKHAISINHs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAUBE")]
		public EntitySet<GIAYKHAISINH> GIAYKHAISINHs
		{
			get
			{
				return this._GIAYKHAISINHs;
			}
			set
			{
				this._GIAYKHAISINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYKHAISINH1", Storage="_GIAYKHAISINHs1", ThisKey="MANHANKHAU", OtherKey="MANHANKHAUME")]
		public EntitySet<GIAYKHAISINH> GIAYKHAISINHs1
		{
			get
			{
				return this._GIAYKHAISINHs1;
			}
			set
			{
				this._GIAYKHAISINHs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_GIAYTAMVANG", Storage="_GIAYTAMVANGs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU")]
		public EntitySet<GIAYTAMVANG> GIAYTAMVANGs
		{
			get
			{
				return this._GIAYTAMVANGs;
			}
			set
			{
				this._GIAYTAMVANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUNHAPKHAU", Storage="_PHIEUNHAPKHAUs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU")]
		public EntitySet<PHIEUNHAPKHAU> PHIEUNHAPKHAUs
		{
			get
			{
				return this._PHIEUNHAPKHAUs;
			}
			set
			{
				this._PHIEUNHAPKHAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTACHKHAU", Storage="_PHIEUTACHKHAUs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU")]
		public EntitySet<PHIEUTACHKHAU> PHIEUTACHKHAUs
		{
			get
			{
				return this._PHIEUTACHKHAUs;
			}
			set
			{
				this._PHIEUTACHKHAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTHAYDOICHUHO", Storage="_PHIEUTHAYDOICHUHOs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU")]
		public EntitySet<PHIEUTHAYDOICHUHO> PHIEUTHAYDOICHUHOs
		{
			get
			{
				return this._PHIEUTHAYDOICHUHOs;
			}
			set
			{
				this._PHIEUTHAYDOICHUHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTU", Storage="_PHIEUTUs", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU")]
		public EntitySet<PHIEUTU> PHIEUTUs
		{
			get
			{
				return this._PHIEUTUs;
			}
			set
			{
				this._PHIEUTUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_NHANKHAU", Storage="_SOHOKHAU", ThisKey="MASHK", OtherKey="MASHK", IsForeignKey=true)]
		public SOHOKHAU SOHOKHAU
		{
			get
			{
				return this._SOHOKHAU.Entity;
			}
			set
			{
				SOHOKHAU previousValue = this._SOHOKHAU.Entity;
				if (((previousValue != value) 
							|| (this._SOHOKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOHOKHAU.Entity = null;
						previousValue.NHANKHAUs.Remove(this);
					}
					this._SOHOKHAU.Entity = value;
					if ((value != null))
					{
						value.NHANKHAUs.Add(this);
						this._MASHK = value.MASHK;
					}
					else
					{
						this._MASHK = default(Nullable<int>);
					}
					this.SendPropertyChanged("SOHOKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYKHAISINHs(GIAYKHAISINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_GIAYKHAISINHs(GIAYKHAISINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_GIAYKHAISINHs1(GIAYKHAISINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU1 = this;
		}
		
		private void detach_GIAYKHAISINHs1(GIAYKHAISINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU1 = null;
		}
		
		private void attach_GIAYTAMVANGs(GIAYTAMVANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_GIAYTAMVANGs(GIAYTAMVANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_PHIEUNHAPKHAUs(PHIEUNHAPKHAU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_PHIEUNHAPKHAUs(PHIEUNHAPKHAU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_PHIEUTACHKHAUs(PHIEUTACHKHAU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_PHIEUTACHKHAUs(PHIEUTACHKHAU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_PHIEUTHAYDOICHUHOs(PHIEUTHAYDOICHUHO entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_PHIEUTHAYDOICHUHOs(PHIEUTHAYDOICHUHO entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
		
		private void attach_PHIEUTUs(PHIEUTU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = this;
		}
		
		private void detach_PHIEUTUs(PHIEUTU entity)
		{
			this.SendPropertyChanging();
			entity.NHANKHAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPKHAU")]
	public partial class PHIEUNHAPKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private int _MASHK;
		
		private int _MAPHIEUNHAPKHAU;
		
		private string _NOICHUYENDI;
		
		private System.Nullable<System.DateTime> _NGAYCHUYENDEN;
		
		private string _LYDOCHUYENDEN;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
		private EntityRef<SOHOKHAU> _SOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMASHKChanging(int value);
    partial void OnMASHKChanged();
    partial void OnMAPHIEUNHAPKHAUChanging(int value);
    partial void OnMAPHIEUNHAPKHAUChanged();
    partial void OnNOICHUYENDIChanging(string value);
    partial void OnNOICHUYENDIChanged();
    partial void OnNGAYCHUYENDENChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCHUYENDENChanged();
    partial void OnLYDOCHUYENDENChanging(string value);
    partial void OnLYDOCHUYENDENChanged();
    #endregion
		
		public PHIEUNHAPKHAU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			this._SOHOKHAU = default(EntityRef<SOHOKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASHK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MASHK
		{
			get
			{
				return this._MASHK;
			}
			set
			{
				if ((this._MASHK != value))
				{
					if (this._SOHOKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASHKChanging(value);
					this.SendPropertyChanging();
					this._MASHK = value;
					this.SendPropertyChanged("MASHK");
					this.OnMASHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUNHAPKHAU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUNHAPKHAU
		{
			get
			{
				return this._MAPHIEUNHAPKHAU;
			}
			set
			{
				if ((this._MAPHIEUNHAPKHAU != value))
				{
					this.OnMAPHIEUNHAPKHAUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUNHAPKHAU = value;
					this.SendPropertyChanged("MAPHIEUNHAPKHAU");
					this.OnMAPHIEUNHAPKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICHUYENDI", DbType="Char(256)")]
		public string NOICHUYENDI
		{
			get
			{
				return this._NOICHUYENDI;
			}
			set
			{
				if ((this._NOICHUYENDI != value))
				{
					this.OnNOICHUYENDIChanging(value);
					this.SendPropertyChanging();
					this._NOICHUYENDI = value;
					this.SendPropertyChanged("NOICHUYENDI");
					this.OnNOICHUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCHUYENDEN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCHUYENDEN
		{
			get
			{
				return this._NGAYCHUYENDEN;
			}
			set
			{
				if ((this._NGAYCHUYENDEN != value))
				{
					this.OnNGAYCHUYENDENChanging(value);
					this.SendPropertyChanging();
					this._NGAYCHUYENDEN = value;
					this.SendPropertyChanged("NGAYCHUYENDEN");
					this.OnNGAYCHUYENDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDOCHUYENDEN", DbType="Char(256)")]
		public string LYDOCHUYENDEN
		{
			get
			{
				return this._LYDOCHUYENDEN;
			}
			set
			{
				if ((this._LYDOCHUYENDEN != value))
				{
					this.OnLYDOCHUYENDENChanging(value);
					this.SendPropertyChanging();
					this._LYDOCHUYENDEN = value;
					this.SendPropertyChanged("LYDOCHUYENDEN");
					this.OnLYDOCHUYENDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUNHAPKHAU", Storage="_NHANKHAU", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.PHIEUNHAPKHAUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHAUs.Add(this);
						this._MANHANKHAU = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAU = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_PHIEUNHAPKHAU", Storage="_SOHOKHAU", ThisKey="MASHK", OtherKey="MASHK", IsForeignKey=true)]
		public SOHOKHAU SOHOKHAU
		{
			get
			{
				return this._SOHOKHAU.Entity;
			}
			set
			{
				SOHOKHAU previousValue = this._SOHOKHAU.Entity;
				if (((previousValue != value) 
							|| (this._SOHOKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOHOKHAU.Entity = null;
						previousValue.PHIEUNHAPKHAUs.Remove(this);
					}
					this._SOHOKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHAUs.Add(this);
						this._MASHK = value.MASHK;
					}
					else
					{
						this._MASHK = default(int);
					}
					this.SendPropertyChanged("SOHOKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTACHKHAU")]
	public partial class PHIEUTACHKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private int _MAPHIEUTACHKHAU;
		
		private System.Nullable<System.DateTime> _NGAYCHUYENDI;
		
		private string _NOICHUYENDI;
		
		private string _LYDOCHUYENDI;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMAPHIEUTACHKHAUChanging(int value);
    partial void OnMAPHIEUTACHKHAUChanged();
    partial void OnNGAYCHUYENDIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCHUYENDIChanged();
    partial void OnNOICHUYENDIChanging(string value);
    partial void OnNOICHUYENDIChanged();
    partial void OnLYDOCHUYENDIChanging(string value);
    partial void OnLYDOCHUYENDIChanged();
    #endregion
		
		public PHIEUTACHKHAU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTACHKHAU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUTACHKHAU
		{
			get
			{
				return this._MAPHIEUTACHKHAU;
			}
			set
			{
				if ((this._MAPHIEUTACHKHAU != value))
				{
					this.OnMAPHIEUTACHKHAUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTACHKHAU = value;
					this.SendPropertyChanged("MAPHIEUTACHKHAU");
					this.OnMAPHIEUTACHKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCHUYENDI", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCHUYENDI
		{
			get
			{
				return this._NGAYCHUYENDI;
			}
			set
			{
				if ((this._NGAYCHUYENDI != value))
				{
					this.OnNGAYCHUYENDIChanging(value);
					this.SendPropertyChanging();
					this._NGAYCHUYENDI = value;
					this.SendPropertyChanged("NGAYCHUYENDI");
					this.OnNGAYCHUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICHUYENDI", DbType="Char(256)")]
		public string NOICHUYENDI
		{
			get
			{
				return this._NOICHUYENDI;
			}
			set
			{
				if ((this._NOICHUYENDI != value))
				{
					this.OnNOICHUYENDIChanging(value);
					this.SendPropertyChanging();
					this._NOICHUYENDI = value;
					this.SendPropertyChanged("NOICHUYENDI");
					this.OnNOICHUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDOCHUYENDI", DbType="Char(256)")]
		public string LYDOCHUYENDI
		{
			get
			{
				return this._LYDOCHUYENDI;
			}
			set
			{
				if ((this._LYDOCHUYENDI != value))
				{
					this.OnLYDOCHUYENDIChanging(value);
					this.SendPropertyChanging();
					this._LYDOCHUYENDI = value;
					this.SendPropertyChanged("LYDOCHUYENDI");
					this.OnLYDOCHUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTACHKHAU", Storage="_NHANKHAU", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.PHIEUTACHKHAUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUTACHKHAUs.Add(this);
						this._MANHANKHAU = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAU = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHAYDOICHUHO")]
	public partial class PHIEUTHAYDOICHUHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private int _MASHK;
		
		private int _MAPHIEUTHAYDOICHUHO;
		
		private System.Nullable<System.DateTime> _NGAYDOI;
		
		private string _LYDO;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
		private EntityRef<SOHOKHAU> _SOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMASHKChanging(int value);
    partial void OnMASHKChanged();
    partial void OnMAPHIEUTHAYDOICHUHOChanging(int value);
    partial void OnMAPHIEUTHAYDOICHUHOChanged();
    partial void OnNGAYDOIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDOIChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    #endregion
		
		public PHIEUTHAYDOICHUHO()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			this._SOHOKHAU = default(EntityRef<SOHOKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASHK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MASHK
		{
			get
			{
				return this._MASHK;
			}
			set
			{
				if ((this._MASHK != value))
				{
					if (this._SOHOKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASHKChanging(value);
					this.SendPropertyChanging();
					this._MASHK = value;
					this.SendPropertyChanged("MASHK");
					this.OnMASHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTHAYDOICHUHO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUTHAYDOICHUHO
		{
			get
			{
				return this._MAPHIEUTHAYDOICHUHO;
			}
			set
			{
				if ((this._MAPHIEUTHAYDOICHUHO != value))
				{
					this.OnMAPHIEUTHAYDOICHUHOChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTHAYDOICHUHO = value;
					this.SendPropertyChanged("MAPHIEUTHAYDOICHUHO");
					this.OnMAPHIEUTHAYDOICHUHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDOI", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYDOI
		{
			get
			{
				return this._NGAYDOI;
			}
			set
			{
				if ((this._NGAYDOI != value))
				{
					this.OnNGAYDOIChanging(value);
					this.SendPropertyChanging();
					this._NGAYDOI = value;
					this.SendPropertyChanged("NGAYDOI");
					this.OnNGAYDOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="Char(256)")]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTHAYDOICHUHO", Storage="_NHANKHAU", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.PHIEUTHAYDOICHUHOs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHAYDOICHUHOs.Add(this);
						this._MANHANKHAU = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAU = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_PHIEUTHAYDOICHUHO", Storage="_SOHOKHAU", ThisKey="MASHK", OtherKey="MASHK", IsForeignKey=true)]
		public SOHOKHAU SOHOKHAU
		{
			get
			{
				return this._SOHOKHAU.Entity;
			}
			set
			{
				SOHOKHAU previousValue = this._SOHOKHAU.Entity;
				if (((previousValue != value) 
							|| (this._SOHOKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOHOKHAU.Entity = null;
						previousValue.PHIEUTHAYDOICHUHOs.Remove(this);
					}
					this._SOHOKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHAYDOICHUHOs.Add(this);
						this._MASHK = value.MASHK;
					}
					else
					{
						this._MASHK = default(int);
					}
					this.SendPropertyChanged("SOHOKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTU")]
	public partial class PHIEUTU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHANKHAU;
		
		private int _MAPHIEUTU;
		
		private System.Nullable<System.DateTime> _NGAYMAT;
		
		private string _LYDOMAT;
		
		private EntityRef<NHANKHAU> _NHANKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANKHAUChanging(int value);
    partial void OnMANHANKHAUChanged();
    partial void OnMAPHIEUTUChanging(int value);
    partial void OnMAPHIEUTUChanged();
    partial void OnNGAYMATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYMATChanged();
    partial void OnLYDOMATChanging(string value);
    partial void OnLYDOMATChanged();
    #endregion
		
		public PHIEUTU()
		{
			this._NHANKHAU = default(EntityRef<NHANKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANKHAU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHANKHAU
		{
			get
			{
				return this._MANHANKHAU;
			}
			set
			{
				if ((this._MANHANKHAU != value))
				{
					if (this._NHANKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANKHAUChanging(value);
					this.SendPropertyChanging();
					this._MANHANKHAU = value;
					this.SendPropertyChanged("MANHANKHAU");
					this.OnMANHANKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUTU
		{
			get
			{
				return this._MAPHIEUTU;
			}
			set
			{
				if ((this._MAPHIEUTU != value))
				{
					this.OnMAPHIEUTUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTU = value;
					this.SendPropertyChanged("MAPHIEUTU");
					this.OnMAPHIEUTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYMAT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYMAT
		{
			get
			{
				return this._NGAYMAT;
			}
			set
			{
				if ((this._NGAYMAT != value))
				{
					this.OnNGAYMATChanging(value);
					this.SendPropertyChanging();
					this._NGAYMAT = value;
					this.SendPropertyChanged("NGAYMAT");
					this.OnNGAYMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDOMAT", DbType="Char(256)")]
		public string LYDOMAT
		{
			get
			{
				return this._LYDOMAT;
			}
			set
			{
				if ((this._LYDOMAT != value))
				{
					this.OnLYDOMATChanging(value);
					this.SendPropertyChanging();
					this._LYDOMAT = value;
					this.SendPropertyChanged("LYDOMAT");
					this.OnLYDOMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANKHAU_PHIEUTU", Storage="_NHANKHAU", ThisKey="MANHANKHAU", OtherKey="MANHANKHAU", IsForeignKey=true)]
		public NHANKHAU NHANKHAU
		{
			get
			{
				return this._NHANKHAU.Entity;
			}
			set
			{
				NHANKHAU previousValue = this._NHANKHAU.Entity;
				if (((previousValue != value) 
							|| (this._NHANKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANKHAU.Entity = null;
						previousValue.PHIEUTUs.Remove(this);
					}
					this._NHANKHAU.Entity = value;
					if ((value != null))
					{
						value.PHIEUTUs.Add(this);
						this._MANHANKHAU = value.MANHANKHAU;
					}
					else
					{
						this._MANHANKHAU = default(int);
					}
					this.SendPropertyChanged("NHANKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOHOKHAU")]
	public partial class SOHOKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MASHK;
		
		private string _SONHA;
		
		private string _DUONG;
		
		private EntitySet<NHANKHAU> _NHANKHAUs;
		
		private EntitySet<PHIEUNHAPKHAU> _PHIEUNHAPKHAUs;
		
		private EntitySet<PHIEUTHAYDOICHUHO> _PHIEUTHAYDOICHUHOs;
		
		private EntitySet<SOTAMTRU> _SOTAMTRUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASHKChanging(int value);
    partial void OnMASHKChanged();
    partial void OnSONHAChanging(string value);
    partial void OnSONHAChanged();
    partial void OnDUONGChanging(string value);
    partial void OnDUONGChanged();
    #endregion
		
		public SOHOKHAU()
		{
			this._NHANKHAUs = new EntitySet<NHANKHAU>(new Action<NHANKHAU>(this.attach_NHANKHAUs), new Action<NHANKHAU>(this.detach_NHANKHAUs));
			this._PHIEUNHAPKHAUs = new EntitySet<PHIEUNHAPKHAU>(new Action<PHIEUNHAPKHAU>(this.attach_PHIEUNHAPKHAUs), new Action<PHIEUNHAPKHAU>(this.detach_PHIEUNHAPKHAUs));
			this._PHIEUTHAYDOICHUHOs = new EntitySet<PHIEUTHAYDOICHUHO>(new Action<PHIEUTHAYDOICHUHO>(this.attach_PHIEUTHAYDOICHUHOs), new Action<PHIEUTHAYDOICHUHO>(this.detach_PHIEUTHAYDOICHUHOs));
			this._SOTAMTRUs = new EntitySet<SOTAMTRU>(new Action<SOTAMTRU>(this.attach_SOTAMTRUs), new Action<SOTAMTRU>(this.detach_SOTAMTRUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASHK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MASHK
		{
			get
			{
				return this._MASHK;
			}
			set
			{
				if ((this._MASHK != value))
				{
					this.OnMASHKChanging(value);
					this.SendPropertyChanging();
					this._MASHK = value;
					this.SendPropertyChanged("MASHK");
					this.OnMASHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONHA", DbType="Char(256)")]
		public string SONHA
		{
			get
			{
				return this._SONHA;
			}
			set
			{
				if ((this._SONHA != value))
				{
					this.OnSONHAChanging(value);
					this.SendPropertyChanging();
					this._SONHA = value;
					this.SendPropertyChanged("SONHA");
					this.OnSONHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUONG", DbType="Char(256)")]
		public string DUONG
		{
			get
			{
				return this._DUONG;
			}
			set
			{
				if ((this._DUONG != value))
				{
					this.OnDUONGChanging(value);
					this.SendPropertyChanging();
					this._DUONG = value;
					this.SendPropertyChanged("DUONG");
					this.OnDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_NHANKHAU", Storage="_NHANKHAUs", ThisKey="MASHK", OtherKey="MASHK")]
		public EntitySet<NHANKHAU> NHANKHAUs
		{
			get
			{
				return this._NHANKHAUs;
			}
			set
			{
				this._NHANKHAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_PHIEUNHAPKHAU", Storage="_PHIEUNHAPKHAUs", ThisKey="MASHK", OtherKey="MASHK")]
		public EntitySet<PHIEUNHAPKHAU> PHIEUNHAPKHAUs
		{
			get
			{
				return this._PHIEUNHAPKHAUs;
			}
			set
			{
				this._PHIEUNHAPKHAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_PHIEUTHAYDOICHUHO", Storage="_PHIEUTHAYDOICHUHOs", ThisKey="MASHK", OtherKey="MASHK")]
		public EntitySet<PHIEUTHAYDOICHUHO> PHIEUTHAYDOICHUHOs
		{
			get
			{
				return this._PHIEUTHAYDOICHUHOs;
			}
			set
			{
				this._PHIEUTHAYDOICHUHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_SOTAMTRU", Storage="_SOTAMTRUs", ThisKey="MASHK", OtherKey="MASHK")]
		public EntitySet<SOTAMTRU> SOTAMTRUs
		{
			get
			{
				return this._SOTAMTRUs;
			}
			set
			{
				this._SOTAMTRUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANKHAUs(NHANKHAU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = this;
		}
		
		private void detach_NHANKHAUs(NHANKHAU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = null;
		}
		
		private void attach_PHIEUNHAPKHAUs(PHIEUNHAPKHAU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = this;
		}
		
		private void detach_PHIEUNHAPKHAUs(PHIEUNHAPKHAU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = null;
		}
		
		private void attach_PHIEUTHAYDOICHUHOs(PHIEUTHAYDOICHUHO entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = this;
		}
		
		private void detach_PHIEUTHAYDOICHUHOs(PHIEUTHAYDOICHUHO entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = null;
		}
		
		private void attach_SOTAMTRUs(SOTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = this;
		}
		
		private void detach_SOTAMTRUs(SOTAMTRU entity)
		{
			this.SendPropertyChanging();
			entity.SOHOKHAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOTAMTRU")]
	public partial class SOTAMTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MASOTAMTRU;
		
		private int _MASHK;
		
		private string _DIACHITHUONGTRU;
		
		private string _HOTEN;
		
		private string _CMND;
		
		private EntityRef<SOHOKHAU> _SOHOKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASOTAMTRUChanging(int value);
    partial void OnMASOTAMTRUChanged();
    partial void OnMASHKChanging(int value);
    partial void OnMASHKChanged();
    partial void OnDIACHITHUONGTRUChanging(string value);
    partial void OnDIACHITHUONGTRUChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    #endregion
		
		public SOTAMTRU()
		{
			this._SOHOKHAU = default(EntityRef<SOHOKHAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASOTAMTRU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MASOTAMTRU
		{
			get
			{
				return this._MASOTAMTRU;
			}
			set
			{
				if ((this._MASOTAMTRU != value))
				{
					this.OnMASOTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._MASOTAMTRU = value;
					this.SendPropertyChanged("MASOTAMTRU");
					this.OnMASOTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASHK", DbType="Int NOT NULL")]
		public int MASHK
		{
			get
			{
				return this._MASHK;
			}
			set
			{
				if ((this._MASHK != value))
				{
					if (this._SOHOKHAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASHKChanging(value);
					this.SendPropertyChanging();
					this._MASHK = value;
					this.SendPropertyChanged("MASHK");
					this.OnMASHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHITHUONGTRU", DbType="Char(256)")]
		public string DIACHITHUONGTRU
		{
			get
			{
				return this._DIACHITHUONGTRU;
			}
			set
			{
				if ((this._DIACHITHUONGTRU != value))
				{
					this.OnDIACHITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._DIACHITHUONGTRU = value;
					this.SendPropertyChanged("DIACHITHUONGTRU");
					this.OnDIACHITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="Char(256)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SOHOKHAU_SOTAMTRU", Storage="_SOHOKHAU", ThisKey="MASHK", OtherKey="MASHK", IsForeignKey=true)]
		public SOHOKHAU SOHOKHAU
		{
			get
			{
				return this._SOHOKHAU.Entity;
			}
			set
			{
				SOHOKHAU previousValue = this._SOHOKHAU.Entity;
				if (((previousValue != value) 
							|| (this._SOHOKHAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SOHOKHAU.Entity = null;
						previousValue.SOTAMTRUs.Remove(this);
					}
					this._SOHOKHAU.Entity = value;
					if ((value != null))
					{
						value.SOTAMTRUs.Add(this);
						this._MASHK = value.MASHK;
					}
					else
					{
						this._MASHK = default(int);
					}
					this.SendPropertyChanged("SOHOKHAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
